export default listBanks = {
    "success" : true,
    "data" : [
      {
        "id" : 1,
        "linkNote" : "Lưu ý: Thông tin SĐT, CMND/CCCD đăng ký tài khoản ngân hàng Vietcombank cần trùng khớp với thông tin đăng ký tài khoản GHTK",
        "shortName" : "Vietcombank",
        "cardPrefixes" : "970436",
        "code" : "vcb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/11020edaee9044559f1894e678b8ee05.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardNumber,cardHolderName,issueDate,phoneNumber,cardIdentity,createLinkType",
        "name" : "Ngân hàng TMCP Ngoại thương Việt Nam",
        "status" : 1
      },
      {
        "id" : 2,
        "linkNote" : "Lưu ý: Thông tin SĐT, CMND/CCCD đăng ký tài khoản ngân hàng VIB cần trùng khớp với thông tin đăng ký tài khoản GHTK",
        "shortName" : "VIB",
        "cardPrefixes" : "970441",
        "code" : "vib",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/d57cd64da9a24c7eb200fbd3642cfae8.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardNumber,cardIdentity,cardHolderName,createLinkType,phoneNumber",
        "name" : "Ngân hàng TMCP Quốc tế",
        "status" : 1
      },
      {
        "id" : 3,
        "linkNote" : "Lưu ý: Thông tin SĐT, CMND/CCCD đăng ký tài khoản ngân hàng MB cần trùng khớp với thông tin đăng ký tài khoản GHTK",
        "shortName" : "MBBank",
        "cardPrefixes" : "970422",
        "code" : "mb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/a35dae072b824f44b8592065965ed967.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardNumber,cardHolderName,phoneNumber,createLinkType",
        "name" : "Ngân hàng TMCP Quân đội",
        "status" : 1
      },
      {
        "id" : 4,
        "linkNote" : "Lưu ý: Thông tin SĐT, CMND/CCCD đăng ký tài khoản ngân hàng Vietinbank cần trùng khớp với thông tin đăng ký tài khoản GHTK",
        "shortName" : "Vietinbank",
        "cardPrefixes" : "970415",
        "code" : "ctg",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/9880d8f3cc204c78ae8402ca3381f8cc.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardNumber,cardHolderName,issueDate,phoneNumber,createLinkType",
        "name" : "Ngân hàng TMCP Công thương Việt Nam",
        "status" : 1
      },
      {
        "id" : 5,
        "shortName" : "HDBank",
        "cardPrefixes" : "970420,970437",
        "code" : "hdb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/91c8d117bae34ed2aa0a26b4764cb86c.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP phát triển TPHCM",
        "status" : 1
      },
      {
        "id" : 6,
        "shortName" : "NCBBank",
        "cardPrefixes" : "970419",
        "code" : "nvb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/8d27fb15601845a5b0de5c272a3e1167.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Quốc dân",
        "status" : 1
      },
      {
        "id" : 7,
        "linkNote" : "Lưu ý: Thông tin SĐT, CMND/CCCD đăng ký tài khoản ngân hàng MSB cần trùng khớp với thông tin đăng ký tài khoản GHTK",
        "shortName" : "MSB",
        "cardPrefixes" : "970426",
        "code" : "msb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/0ceb0c1b47134722907dac74c5ac8a31.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardNumber,cardHolderName,issueDate,phoneNumber,createLinkType",
        "name" : "Ngân hàng TMCP Hàng Hải Việt Nam",
        "status" : 1
      },
      {
        "id" : 8,
        "shortName" : "VietABank",
        "cardPrefixes" : "970427",
        "code" : "vab",
        "displayOrder" : 1,
        "dateInputType" : 3,
        "logo" : "https://cache.giaohangtietkiem.vn/d/84482ca2024b4bbb96a5473d7dac8a5b.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Việt Á",
        "status" : 1
      },
      {
        "id" : 9,
        "shortName" : "GPBank",
        "cardPrefixes" : "970408",
        "code" : "gpb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/f670ee8214df469c895f322a122b295a.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TNHH MTV Dầu khí toàn cầu",
        "status" : 1
      },
      {
        "id" : 10,
        "shortName" : "Oceanbank",
        "cardPrefixes" : "970414",
        "code" : "ojb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/f36a59a5d1014f90952d0862a072a095.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Đại Dương",
        "status" : 1
      },
      {
        "id" : 11,
        "shortName" : "BacABank",
        "cardPrefixes" : "970409",
        "code" : "nasb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/a8225d6936d94a75b78dc64782329d9b.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Bắc Á",
        "status" : 1
      },
      {
        "id" : 13,
        "shortName" : "ABBank",
        "cardPrefixes" : "970425",
        "code" : "abb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/11fa6b4f59674faea6b22ec7e664ae7b.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP An Bình",
        "status" : 1
      },
      {
        "id" : 14,
        "linkNote" : "Lưu ý: Thông tin SĐT, CMND/CCCD đăng ký tài khoản ngân hàng BIDV cần trùng khớp với thông tin đăng ký tài khoản GHTK",
        "shortName" : "BIDV",
        "cardPrefixes" : "970418",
        "code" : "bidv",
        "displayOrder" : 1,
        "dateInputType" : 3,
        "logo" : "https://cache.giaohangtietkiem.vn/d/188ea509bb504957853743c4503af2e1.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardNumber,cardHolderName,cardIdentity,createLinkType,phoneNumber,issueDate",
        "name" : "Ngân hàng TMCP Đầu tư và phát triển Việt Nam",
        "status" : 1
      },
      {
        "id" : 15,
        "shortName" : "SHB",
        "cardPrefixes" : "970443",
        "code" : "shb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/8b6208e1071c419fb15a21c2eb46b48d.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Sài Gòn Hà Nội",
        "status" : 1
      },
      {
        "id" : 16,
        "shortName" : "Baovietbank",
        "cardPrefixes" : "970438",
        "code" : "bvb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/e2d9bfa05cb74cc2a2eec0fb257138c6.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Bảo Việt",
        "status" : 1
      },
      {
        "id" : 17,
        "shortName" : "LienVietPostBank",
        "cardPrefixes" : "970449",
        "code" : "lpb",
        "displayOrder" : 1,
        "dateInputType" : 3,
        "logo" : "https://cache.giaohangtietkiem.vn/d/6cd015d1e0af4266a3aafda1a4c22982.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Bưu điện Liên Việt",
        "status" : 1
      },
      {
        "id" : 18,
        "shortName" : "TPBank",
        "cardPrefixes" : "970423",
        "code" : "tpb",
        "displayOrder" : 1,
        "dateInputType" : 3,
        "logo" : "https://cache.giaohangtietkiem.vn/d/a2f7787ca9ad4dc3a0cb36aff80a791a.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Tiên Phong",
        "status" : 1
      },
      {
        "id" : 19,
        "linkNote" : "Số điện thoại đăng ký tại {{ bankName }} phải là {{ mobile }}. Tên chủ tài khoản trùng khớp với thông tin đã đăng ký tại ngân hàng",
        "shortName" : "Agribank",
        "cardPrefixes" : "970405",
        "code" : "varb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/61540e967af24a0a853c549d379ee9e5.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardNumber,cardHolderName,phoneNumber,createLinkType",
        "name" : "Ngân hàng Nông Nghiệp và PTNT Việt Nam",
        "status" : 1
      },
      {
        "id" : 20,
        "shortName" : "SCB",
        "cardPrefixes" : "970429",
        "code" : "scb",
        "displayOrder" : 1,
        "dateInputType" : 3,
        "logo" : "https://cache.giaohangtietkiem.vn/d/8900f9fa7b004bc39cd87ee580bfaf23.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Sài Gòn",
        "status" : 1
      },
      {
        "id" : 21,
        "shortName" : "KienLongBank",
        "cardPrefixes" : "970452",
        "code" : "klb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/47b075e4966f4f889045fdec7327659e.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Kiên Long",
        "status" : 1
      },
      {
        "id" : 22,
        "shortName" : "SeABank",
        "cardPrefixes" : "970468,970440",
        "code" : "seab",
        "displayOrder" : 1,
        "dateInputType" : 2,
        "logo" : "https://cache.giaohangtietkiem.vn/d/90860297c30140988665382e49b835e1.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Đông Nam Á",
        "status" : 1
      },
      {
        "id" : 23,
        "shortName" : "VRBank",
        "cardPrefixes" : "970421",
        "code" : "vrb",
        "displayOrder" : 1,
        "dateInputType" : 2,
        "logo" : "https://cache.giaohangtietkiem.vn/d/3e11860172c643f0995d0b3c42f74403.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng Liên doanh Việt Nga",
        "status" : 1
      },
      {
        "id" : 24,
        "shortName" : "PublicBank",
        "cardPrefixes" : "970439",
        "code" : "pbvn",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/239ac3b459bb48888adbcc23eacad48e.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TNHH MTV PUBLIC Việt Nam",
        "status" : 1
      },
      {
        "id" : 25,
        "shortName" : "NamABank",
        "cardPrefixes" : "970428",
        "code" : "nab",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/dbcf3f0737754ad08efb69acad92b8fa.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP NAM Á",
        "status" : 1
      },
      {
        "id" : 26,
        "shortName" : "PVcomBank",
        "cardPrefixes" : "970412",
        "code" : "pvcb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/82e42cbddb174b68bf05709ed8abbdf6.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Đại Chúng Việt Nam",
        "status" : 1
      },
      {
        "id" : 27,
        "shortName" : "SGB",
        "cardPrefixes" : "970400",
        "code" : "sgb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/290faf2ad15945fb80deda36ae950c05.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng Sài Gòn Công Thương",
        "status" : 1
      },
      {
        "id" : 28,
        "linkNote" : "",
        "shortName" : "Techcombank",
        "cardPrefixes" : "970407",
        "code" : "tcb",
        "displayOrder" : 1,
        "dateInputType" : 2,
        "logo" : "https://cache.giaohangtietkiem.vn/d/bb644193f06842efaab4eeeb94c88392.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardIdentity,cardHolderName,phoneNumber",
        "name" : "Ngân hàng TMCP Kỹ thương Việt Nam",
        "status" : 1
      },
      {
        "id" : 29,
        "shortName" : "Eximbank",
        "cardPrefixes" : "970431",
        "code" : "eib",
        "displayOrder" : 1,
        "dateInputType" : 2,
        "logo" : "https://cache.giaohangtietkiem.vn/d/06297fc7a9404a5c93ba9588ab5b74a7.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Xuất nhập nhẩu Việt Nam",
        "status" : 1
      },
      {
        "id" : 30,
        "linkNote" : "Lưu ý: Thông tin SĐT, CMND/CCCD đăng ký tài khoản ngân hàng ACB cần trùng khớp với thông tin đăng ký tài khoản GHTK",
        "shortName" : "ACB",
        "cardPrefixes" : "970416",
        "code" : "acb",
        "displayOrder" : 1,
        "dateInputType" : 2,
        "logo" : "https://cache.giaohangtietkiem.vn/d/2ec0045a32864b1d851a4971ef3660a3.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardHolderName,phoneNumber",
        "name" : "Ngân hàng TMCP Á châu",
        "status" : 1
      },
      {
        "id" : 31,
        "linkNote" : "Lưu ý: Thông tin SĐT, CMND/CCCD đăng ký tài khoản ngân hàng Sacombank cần trùng khớp với thông tin đăng ký tài khoản GHTK",
        "shortName" : "Sacombank",
        "cardPrefixes" : "970403",
        "code" : "stb",
        "displayOrder" : 1,
        "dateInputType" : 3,
        "logo" : "https://cache.giaohangtietkiem.vn/d/63eb5e56aff24f359182c78ca1d4d94c.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardHolderName,phoneNumber",
        "name" : "Ngân hàng TMCP Sài gòn Thương tín",
        "status" : 1
      },
      {
        "id" : 32,
        "linkNote" : "Lưu ý: Thông tin SĐT, CMND/CCCD đăng ký tài khoản ngân hàng VPBank cần trùng khớp với thông tin đăng ký tài khoản GHTK",
        "shortName" : "VPBank",
        "cardPrefixes" : "970432",
        "code" : "vpb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/2c4a71c8a1a74cb4bb8598f123e9fd8b.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Việt Nam Thịnh vượng",
        "status" : 1
      },
      {
        "id" : 33,
        "linkNote" : "Lưu ý: Thông tin SĐT, CMND/CCCD đăng ký tài khoản ngân hàng OCB cần trùng khớp với thông tin đăng ký tài khoản GHTK",
        "shortName" : "OCB",
        "cardPrefixes" : "970448",
        "code" : "ocb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/e05c08b8642a42e0a23bbb508370df1d.png",
        "isLinked" : false,
        "isNapas" : 0,
        "isDirect" : 1,
        "createLink" : "bankCode,cardNumber,cardIdentity,cardIdentityType,cardHolderName,createLinkType,phoneNumber",
        "name" : "Ngân hàng TMCP Phương Đông",
        "status" : 1
      },
      {
        "id" : 34,
        "shortName" : "PGBank",
        "cardPrefixes" : "970430",
        "code" : "pgb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/5e4ae6edd33d41e2b7930609c9289235.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TNHH MTV Xăng dầu Petrolimex",
        "status" : 1
      },
      {
        "id" : 35,
        "shortName" : "UOB",
        "cardPrefixes" : "970458",
        "code" : "uob",
        "displayOrder" : 1,
        "dateInputType" : 2,
        "logo" : "https://cache.giaohangtietkiem.vn/d/db9bbbf5b1fd405b9957d349175456be.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TNHH MTV United Overseas Bank (Việt Nam)",
        "status" : 1
      },
      {
        "id" : 36,
        "shortName" : "Indovina",
        "cardPrefixes" : "970434",
        "code" : "ivb",
        "displayOrder" : 1,
        "dateInputType" : 2,
        "logo" : "https://cache.giaohangtietkiem.vn/d/4a184056594a4af3967a0e46192f1d42.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TNHH Indovina",
        "status" : 1
      },
      {
        "id" : 37,
        "shortName" : "WooriBank",
        "cardPrefixes" : "970457",
        "code" : "woo",
        "displayOrder" : 1,
        "dateInputType" : 3,
        "logo" : "https://cache.giaohangtietkiem.vn/d/cfc4ff28e05845b99f490b06ee4011d7.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TNHH Woori bank",
        "status" : 1
      },
      {
        "id" : 38,
        "shortName" : "ShinhanBank",
        "cardPrefixes" : "970424",
        "code" : "svb",
        "displayOrder" : 1,
        "dateInputType" : 3,
        "logo" : "https://cache.giaohangtietkiem.vn/d/51df9f3bad104e30a672a0f24d5dd4d7.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TNHH MTV Shinhan (Việt Nam)",
        "status" : 1
      },
      {
        "id" : 39,
        "shortName" : "BanVietBank",
        "cardPrefixes" : "970454",
        "code" : "vccb",
        "displayOrder" : 1,
        "dateInputType" : 1,
        "logo" : "https://cache.giaohangtietkiem.vn/d/ba83568162e14edc81ed2e1e072f530e.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Bản Việt",
        "status" : 1
      },
      {
        "id" : 40,
        "shortName" : "VietBank",
        "cardPrefixes" : "970433",
        "code" : "vb",
        "displayOrder" : 1,
        "dateInputType" : 2,
        "logo" : "https://cache.giaohangtietkiem.vn/d/81c2d4555ba845f3a0c119fcd77a193c.png",
        "isLinked" : false,
        "isNapas" : 1,
        "isDirect" : 0,
        "name" : "Ngân hàng TMCP Việt Nam Thương Tín",
        "status" : 1
      }
    ]
  }